#include "currency.h"

namespace mc {
//    namespace impl {
//        // ISO 4217 Currency Codes
//        // Code Country Name
//        // More effective will be vector structure
//        extern const std::map<currency, std::string> currency_name_;
//
//        // ISO 4217 Currency Codes
//        // Code Short Name
//        // More effective will be vector structure
//        extern const std::map<currency, std::string> currency_to_shortname_;
//        extern const std::map<std::string, currency> shortname_to_currency_;
//    }
    namespace impl {
        const std::map<currency, std::string> currency_name_ = {
            {currency::AED, "United Arab Emirates Dirham"},
            {currency::AFN, "Afghanistan Afghani"},
            {currency::ALL, "Albania Lek"},
            {currency::AMD, "Armenia Dram"},
            {currency::ANG, "Netherlands Antilles Guilder"},
            {currency::AOA, "Angola Kwanza"},
            {currency::ARS, "Argentina Peso"},
            {currency::AUD, "Australia Dollar"},
            {currency::AWG, "Aruba Guilder"},
            {currency::AZN, "Azerbaijan Manat"},
            {currency::BAM, "Bosnia and Herzegovina Convertible Marka"},
            {currency::BBD, "Barbados Dollar"},
            {currency::BDT, "Bangladesh Taka"},
            {currency::BGN, "Bulgaria Lev"},
            {currency::BHD, "Bahrain Dinar"},
            {currency::BIF, "Burundi Franc"},
            {currency::BMD, "Bermuda Dollar"},
            {currency::BND, "Brunei Darussalam Dollar"},
            {currency::BOB, "Bolivia Bolíviano"},
            {currency::BRL, "Brazil Real"},
            {currency::BSD, "Bahamas Dollar"},
            {currency::BTN, "Bhutan Ngultrum"},
            {currency::BWP, "Botswana Pula"},
            {currency::BYN, "Belarus Ruble"},
            {currency::BZD, "Belize Dollar"},
            {currency::CAD, "Canada Dollar"},
            {currency::CDF, "Congo / Kinshasa Franc"},
            {currency::CHF, "Switzerland Franc"},
            {currency::CLP, "Chile Peso"},
            {currency::CNY, "China Yuan Renminbi"},
            {currency::COP, "Colombia Peso"},
            {currency::CRC, "Costa Rica Colon"},
            {currency::CUC, "Cuba Convertible Peso"},
            {currency::CUP, "Cuba Peso"},
            {currency::CVE, "Cape Verde Escudo"},
            {currency::CZK, "Czech Republic Koruna"},
            {currency::DJF, "Djibouti Franc"},
            {currency::DKK, "Denmark Krone"},
            {currency::DOP, "Dominican Republic Peso"},
            {currency::DZD, "Algeria Dinar"},
            {currency::EGP, "Egypt Pound"},
            {currency::ERN, "Eritrea Nakfa"},
            {currency::ETB, "Ethiopia Birr"},
            {currency::EUR, "Euro Member Countries"},
            {currency::FJD, "Fiji Dollar"},
            {currency::FKP, "Falkland Islands(Malvinas) Pound"},
            {currency::GBP, "United Kingdom Pound"},
            {currency::GEL, "Georgia Lari"},
            {currency::GGP, "Guernsey Pound"},
            {currency::GHS, "Ghana Cedi"},
            {currency::GIP, "Gibraltar Pound"},
            {currency::GMD, "Gambia Dalasi"},
            {currency::GNF, "Guinea Franc"},
            {currency::GTQ, "Guatemala Quetzal"},
            {currency::GYD, "Guyana Dollar"},
            {currency::HKD, "Hong Kong Dollar"},
            {currency::HNL, "Honduras Lempira"},
            {currency::HRK, "Croatia Kuna"},
            {currency::HTG, "Haiti Gourde"},
            {currency::HUF, "Hungary Forint"},
            {currency::IDR, "Indonesia Rupiah"},
            {currency::ILS, "Israel Shekel"},
            {currency::IMP, "Isle of Man Pound"},
            {currency::INR, "India Rupee"},
            {currency::IQD, "Iraq Dinar"},
            {currency::IRR, "Iran Rial"},
            {currency::ISK, "Iceland Krona"},
            {currency::JEP, "Jersey Pound"},
            {currency::JMD, "Jamaica Dollar"},
            {currency::JOD, "Jordan Dinar"},
            {currency::JPY, "Japan Yen"},
            {currency::KES, "Kenya Shilling"},
            {currency::KGS, "Kyrgyzstan Som"},
            {currency::KHR, "Cambodia Riel"},
            {currency::KMF, "Comorian Franc"},
            {currency::KPW, "Korea(North) Won"},
            {currency::KRW, "Korea(South) Won"},
            {currency::KWD, "Kuwait Dinar"},
            {currency::KYD, "Cayman Islands Dollar"},
            {currency::KZT, "Kazakhstan Tenge"},
            {currency::LAK, "Laos Kip"},
            {currency::LBP, "Lebanon Pound"},
            {currency::LKR, "Sri Lanka Rupee"},
            {currency::LRD, "Liberia Dollar"},
            {currency::LSL, "Lesotho Loti"},
            {currency::LYD, "Libya Dinar"},
            {currency::MAD, "Morocco Dirham"},
            {currency::MDL, "Moldova Leu"},
            {currency::MGA, "Madagascar Ariary"},
            {currency::MKD, "Macedonia Denar"},
            {currency::MMK, "Myanmar(Burma) Kyat"},
            {currency::MNT, "Mongolia Tughrik"},
            {currency::MOP, "Macau Pataca"},
            {currency::MRU, "Mauritania Ouguiya"},
            {currency::MUR, "Mauritius Rupee"},
            {currency::MVR, "Maldives(Maldive Islands) Rufiyaa"},
            {currency::MWK, "Malawi Kwacha"},
            {currency::MXN, "Mexico Peso"},
            {currency::MYR, "Malaysia Ringgit"},
            {currency::MZN, "Mozambique Metical"},
            {currency::NAD, "Namibia Dollar"},
            {currency::NGN, "Nigeria Naira"},
            {currency::NIO, "Nicaragua Cordoba"},
            {currency::NOK, "Norway Krone"},
            {currency::NPR, "Nepal Rupee"},
            {currency::NZD, "New Zealand Dollar"},
            {currency::OMR, "Oman Rial"},
            {currency::PAB, "Panama Balboa"},
            {currency::PEN, "Peru Sol"},
            {currency::PGK, "Papua New Guinea Kina"},
            {currency::PHP, "Philippines Piso"},
            {currency::PKR, "Pakistan Rupee"},
            {currency::PLN, "Poland Zloty"},
            {currency::PYG, "Paraguay Guarani"},
            {currency::QAR, "Qatar Riyal"},
            {currency::RON, "Romania Leu"},
            {currency::RSD, "Serbia Dinar"},
            {currency::RUB, "Russia Ruble"},
            {currency::RWF, "Rwanda Franc"},
            {currency::SAR, "Saudi Arabia Riyal"},
            {currency::SBD, "Solomon Islands Dollar"},
            {currency::SCR, "Seychelles Rupee"},
            {currency::SDG, "Sudan Pound"},
            {currency::SEK, "Sweden Krona"},
            {currency::SGD, "Singapore Dollar"},
            {currency::SHP, "Saint Helena Pound"},
            {currency::SLL, "Sierra Leone Leone"},
            {currency::SOS, "Somalia Shilling"},
            {currency::SPL, "Seborga Luigino"},
            {currency::SRD, "Suriname Dollar"},
            {currency::STN, "São Tomé and Príncipe Dobra"},
            {currency::SVC, "El Salvador Colon"},
            {currency::SYP, "Syria Pound"},
            {currency::SZL, "Swaziland Lilangeni"},
            {currency::THB, "Thailand Baht"},
            {currency::TJS, "Tajikistan Somoni"},
            {currency::TMT, "Turkmenistan Manat"},
            {currency::TND, "Tunisia Dinar"},
            {currency::TOP, "Tonga Pa'anga"},
            {currency::TRY, "Turkey Lira"},
            {currency::TTD, "Trinidad and Tobago Dollar"},
            {currency::TVD, "Tuvalu Dollar"},
            {currency::TWD, "Taiwan New Dollar"},
            {currency::TZS, "Tanzania Shilling"},
            {currency::UAH, "Ukraine Hryvnia"},
            {currency::UGX, "Uganda Shilling"},
            {currency::USD, "United States Dollar"},
            {currency::UYU, "Uruguay Peso"},
            {currency::UZS, "Uzbekistan Som"},
            {currency::VEF, "Venezuela Bolívar"},
            {currency::VND, "Viet Nam Dong"},
            {currency::VUV, "Vanuatu Vatu"},
            {currency::WST, "Samoa Tala"},
            {currency::XAF, "Communauté Financière Africaine(BEAC) CFA Franc BEAC"},
            {currency::XCD, "East Caribbean Dollar"},
            {currency::XDR, "International Monetary Fund(IMF) Special Drawing Rights"},
            {currency::XOF, "Communauté Financière Africaine(BCEAO) Franc"},
            {currency::XPF, "Comptoirs Français du Pacifique(CFP) Franc"},
            {currency::YER, "Yemen Rial"},
            {currency::ZAR, "South Africa Rand"},
            {currency::ZMW, "Zambia Kwacha"},
            {currency::ZWD, "Zimbabwe Dollar"}
        };

        const std::map<currency, std::string> currency_to_shortname_ = {
            {currency::AED, "AED"},
            {currency::AFN, "AFN"},
            {currency::ALL, "ALL"},
            {currency::AMD, "AMD"},
            {currency::ANG, "ANG"},
            {currency::AOA, "AOA"},
            {currency::ARS, "ARS"},
            {currency::AUD, "AUD"},
            {currency::AWG, "AWG"},
            {currency::AZN, "AZN"},
            {currency::BAM, "BAM"},
            {currency::BBD, "BBD"},
            {currency::BDT, "BDT"},
            {currency::BGN, "BGN"},
            {currency::BHD, "BHD"},
            {currency::BIF, "BIF"},
            {currency::BMD, "BMD"},
            {currency::BND, "BND"},
            {currency::BOB, "BOB"},
            {currency::BRL, "BRL"},
            {currency::BSD, "BSD"},
            {currency::BTN, "BTN"},
            {currency::BWP, "BWP"},
            {currency::BYN, "BYN"},
            {currency::BZD, "BZD"},
            {currency::CAD, "CAD"},
            {currency::CDF, "CDF"},
            {currency::CHF, "CHF"},
            {currency::CLP, "CLP"},
            {currency::CNY, "CNY"},
            {currency::COP, "COP"},
            {currency::CRC, "CRC"},
            {currency::CUC, "CUC"},
            {currency::CUP, "CUP"},
            {currency::CVE, "CVE"},
            {currency::CZK, "CZK"},
            {currency::DJF, "DJF"},
            {currency::DKK, "DKK"},
            {currency::DOP, "DOP"},
            {currency::DZD, "DZD"},
            {currency::EGP, "EGP"},
            {currency::ERN, "ERN"},
            {currency::ETB, "ETB"},
            {currency::EUR, "EUR"},
            {currency::FJD, "FJD"},
            {currency::FKP, "FKP"},
            {currency::GBP, "GBP"},
            {currency::GEL, "GEL"},
            {currency::GGP, "GGP"},
            {currency::GHS, "GHS"},
            {currency::GIP, "GIP"},
            {currency::GMD, "GMD"},
            {currency::GNF, "GNF"},
            {currency::GTQ, "GTQ"},
            {currency::GYD, "GYD"},
            {currency::HKD, "HKD"},
            {currency::HNL, "HNL"},
            {currency::HRK, "HRK"},
            {currency::HTG, "HTG"},
            {currency::HUF, "HUF"},
            {currency::IDR, "IDR"},
            {currency::ILS, "ILS"},
            {currency::IMP, "IMP"},
            {currency::INR, "INR"},
            {currency::IQD, "IQD"},
            {currency::IRR, "IRR"},
            {currency::ISK, "ISK"},
            {currency::JEP, "JEP"},
            {currency::JMD, "JMD"},
            {currency::JOD, "JOD"},
            {currency::JPY, "JPY"},
            {currency::KES, "KES"},
            {currency::KGS, "KGS"},
            {currency::KHR, "KHR"},
            {currency::KMF, "KMF"},
            {currency::KPW, "KPW"},
            {currency::KRW, "KRW"},
            {currency::KWD, "KWD"},
            {currency::KYD, "KYD"},
            {currency::KZT, "KZT"},
            {currency::LAK, "LAK"},
            {currency::LBP, "LBP"},
            {currency::LKR, "LKR"},
            {currency::LRD, "LRD"},
            {currency::LSL, "LSL"},
            {currency::LYD, "LYD"},
            {currency::MAD, "MAD"},
            {currency::MDL, "MDL"},
            {currency::MGA, "MGA"},
            {currency::MKD, "MKD"},
            {currency::MMK, "MMK"},
            {currency::MNT, "MNT"},
            {currency::MOP, "MOP"},
            {currency::MRU, "MRU"},
            {currency::MUR, "MUR"},
            {currency::MVR, "MVR"},
            {currency::MWK, "MWK"},
            {currency::MXN, "MXN"},
            {currency::MYR, "MYR"},
            {currency::MZN, "MZN"},
            {currency::NAD, "NAD"},
            {currency::NGN, "NGN"},
            {currency::NIO, "NIO"},
            {currency::NOK, "NOK"},
            {currency::NPR, "NPR"},
            {currency::NZD, "NZD"},
            {currency::OMR, "OMR"},
            {currency::PAB, "PAB"},
            {currency::PEN, "PEN"},
            {currency::PGK, "PGK"},
            {currency::PHP, "PHP"},
            {currency::PKR, "PKR"},
            {currency::PLN, "PLN"},
            {currency::PYG, "PYG"},
            {currency::QAR, "QAR"},
            {currency::RON, "RON"},
            {currency::RSD, "RSD"},
            {currency::RUB, "RUB"},
            {currency::RWF, "RWF"},
            {currency::SAR, "SAR"},
            {currency::SBD, "SBD"},
            {currency::SCR, "SCR"},
            {currency::SDG, "SDG"},
            {currency::SEK, "SEK"},
            {currency::SGD, "SGD"},
            {currency::SHP, "SHP"},
            {currency::SLL, "SLL"},
            {currency::SOS, "SOS"},
            {currency::SPL, "SPL"},
            {currency::SRD, "SRD"},
            {currency::STN, "STN"},
            {currency::SVC, "SVC"},
            {currency::SYP, "SYP"},
            {currency::SZL, "SZL"},
            {currency::THB, "THB"},
            {currency::TJS, "TJS"},
            {currency::TMT, "TMT"},
            {currency::TND, "TND"},
            {currency::TOP, "TOP"},
            {currency::TRY, "TRY"},
            {currency::TTD, "TTD"},
            {currency::TVD, "TVD"},
            {currency::TWD, "TWD"},
            {currency::TZS, "TZS"},
            {currency::UAH, "UAH"},
            {currency::UGX, "UGX"},
            {currency::USD, "USD"},
            {currency::UYU, "UYU"},
            {currency::UZS, "UZS"},
            {currency::VEF, "VEF"},
            {currency::VND, "VND"},
            {currency::VUV, "VUV"},
            {currency::WST, "WST"},
            {currency::XAF, "XAF"},
            {currency::XCD, "XCD"},
            {currency::XDR, "XDR"},
            {currency::XOF, "XOF"},
            {currency::XPF, "XPF"},
            {currency::YER, "YER"},
            {currency::ZAR, "ZAR"},
            {currency::ZMW, "ZMW"},
            {currency::ZWD, "ZWD"}
        };

        const std::map<std::string, currency> shortname_to_currency_ = {
            {"AED", currency::AED},
            {"AFN", currency::AFN},
            {"ALL", currency::ALL},
            {"AMD", currency::AMD},
            {"ANG", currency::ANG},
            {"AOA", currency::AOA},
            {"ARS", currency::ARS},
            {"AUD", currency::AUD},
            {"AWG", currency::AWG},
            {"AZN", currency::AZN},
            {"BAM", currency::BAM},
            {"BBD", currency::BBD},
            {"BDT", currency::BDT},
            {"BGN", currency::BGN},
            {"BHD", currency::BHD},
            {"BIF", currency::BIF},
            {"BMD", currency::BMD},
            {"BND", currency::BND},
            {"BOB", currency::BOB},
            {"BRL", currency::BRL},
            {"BSD", currency::BSD},
            {"BTN", currency::BTN},
            {"BWP", currency::BWP},
            {"BYN", currency::BYN},
            {"BZD", currency::BZD},
            {"CAD", currency::CAD},
            {"CDF", currency::CDF},
            {"CHF", currency::CHF},
            {"CLP", currency::CLP},
            {"CNY", currency::CNY},
            {"COP", currency::COP},
            {"CRC", currency::CRC},
            {"CUC", currency::CUC},
            {"CUP", currency::CUP},
            {"CVE", currency::CVE},
            {"CZK", currency::CZK},
            {"DJF", currency::DJF},
            {"DKK", currency::DKK},
            {"DOP", currency::DOP},
            {"DZD", currency::DZD},
            {"EGP", currency::EGP},
            {"ERN", currency::ERN},
            {"ETB", currency::ETB},
            {"EUR", currency::EUR},
            {"FJD", currency::FJD},
            {"FKP", currency::FKP},
            {"GBP", currency::GBP},
            {"GEL", currency::GEL},
            {"GGP", currency::GGP},
            {"GHS", currency::GHS},
            {"GIP", currency::GIP},
            {"GMD", currency::GMD},
            {"GNF", currency::GNF},
            {"GTQ", currency::GTQ},
            {"GYD", currency::GYD},
            {"HKD", currency::HKD},
            {"HNL", currency::HNL},
            {"HRK", currency::HRK},
            {"HTG", currency::HTG},
            {"HUF", currency::HUF},
            {"IDR", currency::IDR},
            {"ILS", currency::ILS},
            {"IMP", currency::IMP},
            {"INR", currency::INR},
            {"IQD", currency::IQD},
            {"IRR", currency::IRR},
            {"ISK", currency::ISK},
            {"JEP", currency::JEP},
            {"JMD", currency::JMD},
            {"JOD", currency::JOD},
            {"JPY", currency::JPY},
            {"KES", currency::KES},
            {"KGS", currency::KGS},
            {"KHR", currency::KHR},
            {"KMF", currency::KMF},
            {"KPW", currency::KPW},
            {"KRW", currency::KRW},
            {"KWD", currency::KWD},
            {"KYD", currency::KYD},
            {"KZT", currency::KZT},
            {"LAK", currency::LAK},
            {"LBP", currency::LBP},
            {"LKR", currency::LKR},
            {"LRD", currency::LRD},
            {"LSL", currency::LSL},
            {"LYD", currency::LYD},
            {"MAD", currency::MAD},
            {"MDL", currency::MDL},
            {"MGA", currency::MGA},
            {"MKD", currency::MKD},
            {"MMK", currency::MMK},
            {"MNT", currency::MNT},
            {"MOP", currency::MOP},
            {"MRU", currency::MRU},
            {"MUR", currency::MUR},
            {"MVR", currency::MVR},
            {"MWK", currency::MWK},
            {"MXN", currency::MXN},
            {"MYR", currency::MYR},
            {"MZN", currency::MZN},
            {"NAD", currency::NAD},
            {"NGN", currency::NGN},
            {"NIO", currency::NIO},
            {"NOK", currency::NOK},
            {"NPR", currency::NPR},
            {"NZD", currency::NZD},
            {"OMR", currency::OMR},
            {"PAB", currency::PAB},
            {"PEN", currency::PEN},
            {"PGK", currency::PGK},
            {"PHP", currency::PHP},
            {"PKR", currency::PKR},
            {"PLN", currency::PLN},
            {"PYG", currency::PYG},
            {"QAR", currency::QAR},
            {"RON", currency::RON},
            {"RSD", currency::RSD},
            {"RUB", currency::RUB},
            {"RWF", currency::RWF},
            {"SAR", currency::SAR},
            {"SBD", currency::SBD},
            {"SCR", currency::SCR},
            {"SDG", currency::SDG},
            {"SEK", currency::SEK},
            {"SGD", currency::SGD},
            {"SHP", currency::SHP},
            {"SLL", currency::SLL},
            {"SOS", currency::SOS},
            {"SPL", currency::SPL},
            {"SRD", currency::SRD},
            {"STN", currency::STN},
            {"SVC", currency::SVC},
            {"SYP", currency::SYP},
            {"SZL", currency::SZL},
            {"THB", currency::THB},
            {"TJS", currency::TJS},
            {"TMT", currency::TMT},
            {"TND", currency::TND},
            {"TOP", currency::TOP},
            {"TRY", currency::TRY},
            {"TTD", currency::TTD},
            {"TVD", currency::TVD},
            {"TWD", currency::TWD},
            {"TZS", currency::TZS},
            {"UAH", currency::UAH},
            {"UGX", currency::UGX},
            {"USD", currency::USD},
            {"UYU", currency::UYU},
            {"UZS", currency::UZS},
            {"VEF", currency::VEF},
            {"VND", currency::VND},
            {"VUV", currency::VUV},
            {"WST", currency::WST},
            {"XAF", currency::XAF},
            {"XCD", currency::XCD},
            {"XDR", currency::XDR},
            {"XOF", currency::XOF},
            {"XPF", currency::XPF},
            {"YER", currency::YER},
            {"ZAR", currency::ZAR},
            {"ZMW", currency::ZMW},
            {"ZWD", currency::ZWD}
        };
    }

    std::string to_string(currency c) {
        using namespace impl;
        if (currency_name_.find(c) == currency_name_.end()) {
            throw unknown_currency();
        }
        return currency_name_.at(c);
    }

    std::string to_shortname(currency c) {
        using namespace impl;
        if (currency_name_.find(c) == currency_name_.end()) {
            throw unknown_currency();
        }
        return currency_to_shortname_.at(c);
    }

    currency to_currency(std::string sn) {
        using namespace impl;
        if (shortname_to_currency_.find(sn) == shortname_to_currency_.end()) {
            throw unknown_currency_shortname();
        }
        return shortname_to_currency_.at(sn);
    }

    // exceptions

    const char* unknown_currency::what() const noexcept {
        return "unknown currency";
    }

    const char* unknown_currency_shortname::what() const noexcept {
        return "unknown currency short name";
    }
}