#include "currency.h"

namespace mc {
    const std::map<currency_t, std::string> currency_name = {
        {currency_t::AED, "United Arab Emirates Dirham"},
        {currency_t::AFN, "Afghanistan Afghani"},
        {currency_t::ALL, "Albania Lek"},
        {currency_t::AMD, "Armenia Dram"},
        {currency_t::ANG, "Netherlands Antilles Guilder"},
        {currency_t::AOA, "Angola Kwanza"},
        {currency_t::ARS, "Argentina Peso"},
        {currency_t::AUD, "Australia Dollar"},
        {currency_t::AWG, "Aruba Guilder"},
        {currency_t::AZN, "Azerbaijan Manat"},
        {currency_t::BAM, "Bosnia and Herzegovina Convertible Marka"},
        {currency_t::BBD, "Barbados Dollar"},
        {currency_t::BDT, "Bangladesh Taka"},
        {currency_t::BGN, "Bulgaria Lev"},
        {currency_t::BHD, "Bahrain Dinar"},
        {currency_t::BIF, "Burundi Franc"},
        {currency_t::BMD, "Bermuda Dollar"},
        {currency_t::BND, "Brunei Darussalam Dollar"},
        {currency_t::BOB, "Bolivia Bolíviano"},
        {currency_t::BRL, "Brazil Real"},
        {currency_t::BSD, "Bahamas Dollar"},
        {currency_t::BTN, "Bhutan Ngultrum"},
        {currency_t::BWP, "Botswana Pula"},
        {currency_t::BYN, "Belarus Ruble"},
        {currency_t::BZD, "Belize Dollar"},
        {currency_t::CAD, "Canada Dollar"},
        {currency_t::CDF, "Congo / Kinshasa Franc"},
        {currency_t::CHF, "Switzerland Franc"},
        {currency_t::CLP, "Chile Peso"},
        {currency_t::CNY, "China Yuan Renminbi"},
        {currency_t::COP, "Colombia Peso"},
        {currency_t::CRC, "Costa Rica Colon"},
        {currency_t::CUC, "Cuba Convertible Peso"},
        {currency_t::CUP, "Cuba Peso"},
        {currency_t::CVE, "Cape Verde Escudo"},
        {currency_t::CZK, "Czech Republic Koruna"},
        {currency_t::DJF, "Djibouti Franc"},
        {currency_t::DKK, "Denmark Krone"},
        {currency_t::DOP, "Dominican Republic Peso"},
        {currency_t::DZD, "Algeria Dinar"},
        {currency_t::EGP, "Egypt Pound"},
        {currency_t::ERN, "Eritrea Nakfa"},
        {currency_t::ETB, "Ethiopia Birr"},
        {currency_t::EUR, "Euro Member Countries"},
        {currency_t::FJD, "Fiji Dollar"},
        {currency_t::FKP, "Falkland Islands(Malvinas) Pound"},
        {currency_t::GBP, "United Kingdom Pound"},
        {currency_t::GEL, "Georgia Lari"},
        {currency_t::GGP, "Guernsey Pound"},
        {currency_t::GHS, "Ghana Cedi"},
        {currency_t::GIP, "Gibraltar Pound"},
        {currency_t::GMD, "Gambia Dalasi"},
        {currency_t::GNF, "Guinea Franc"},
        {currency_t::GTQ, "Guatemala Quetzal"},
        {currency_t::GYD, "Guyana Dollar"},
        {currency_t::HKD, "Hong Kong Dollar"},
        {currency_t::HNL, "Honduras Lempira"},
        {currency_t::HRK, "Croatia Kuna"},
        {currency_t::HTG, "Haiti Gourde"},
        {currency_t::HUF, "Hungary Forint"},
        {currency_t::IDR, "Indonesia Rupiah"},
        {currency_t::ILS, "Israel Shekel"},
        {currency_t::IMP, "Isle of Man Pound"},
        {currency_t::INR, "India Rupee"},
        {currency_t::IQD, "Iraq Dinar"},
        {currency_t::IRR, "Iran Rial"},
        {currency_t::ISK, "Iceland Krona"},
        {currency_t::JEP, "Jersey Pound"},
        {currency_t::JMD, "Jamaica Dollar"},
        {currency_t::JOD, "Jordan Dinar"},
        {currency_t::JPY, "Japan Yen"},
        {currency_t::KES, "Kenya Shilling"},
        {currency_t::KGS, "Kyrgyzstan Som"},
        {currency_t::KHR, "Cambodia Riel"},
        {currency_t::KMF, "Comorian Franc"},
        {currency_t::KPW, "Korea(North) Won"},
        {currency_t::KRW, "Korea(South) Won"},
        {currency_t::KWD, "Kuwait Dinar"},
        {currency_t::KYD, "Cayman Islands Dollar"},
        {currency_t::KZT, "Kazakhstan Tenge"},
        {currency_t::LAK, "Laos Kip"},
        {currency_t::LBP, "Lebanon Pound"},
        {currency_t::LKR, "Sri Lanka Rupee"},
        {currency_t::LRD, "Liberia Dollar"},
        {currency_t::LSL, "Lesotho Loti"},
        {currency_t::LYD, "Libya Dinar"},
        {currency_t::MAD, "Morocco Dirham"},
        {currency_t::MDL, "Moldova Leu"},
        {currency_t::MGA, "Madagascar Ariary"},
        {currency_t::MKD, "Macedonia Denar"},
        {currency_t::MMK, "Myanmar(Burma) Kyat"},
        {currency_t::MNT, "Mongolia Tughrik"},
        {currency_t::MOP, "Macau Pataca"},
        {currency_t::MRU, "Mauritania Ouguiya"},
        {currency_t::MUR, "Mauritius Rupee"},
        {currency_t::MVR, "Maldives(Maldive Islands) Rufiyaa"},
        {currency_t::MWK, "Malawi Kwacha"},
        {currency_t::MXN, "Mexico Peso"},
        {currency_t::MYR, "Malaysia Ringgit"},
        {currency_t::MZN, "Mozambique Metical"},
        {currency_t::NAD, "Namibia Dollar"},
        {currency_t::NGN, "Nigeria Naira"},
        {currency_t::NIO, "Nicaragua Cordoba"},
        {currency_t::NOK, "Norway Krone"},
        {currency_t::NPR, "Nepal Rupee"},
        {currency_t::NZD, "New Zealand Dollar"},
        {currency_t::OMR, "Oman Rial"},
        {currency_t::PAB, "Panama Balboa"},
        {currency_t::PEN, "Peru Sol"},
        {currency_t::PGK, "Papua New Guinea Kina"},
        {currency_t::PHP, "Philippines Piso"},
        {currency_t::PKR, "Pakistan Rupee"},
        {currency_t::PLN, "Poland Zloty"},
        {currency_t::PYG, "Paraguay Guarani"},
        {currency_t::QAR, "Qatar Riyal"},
        {currency_t::RON, "Romania Leu"},
        {currency_t::RSD, "Serbia Dinar"},
        {currency_t::RUB, "Russia Ruble"},
        {currency_t::RWF, "Rwanda Franc"},
        {currency_t::SAR, "Saudi Arabia Riyal"},
        {currency_t::SBD, "Solomon Islands Dollar"},
        {currency_t::SCR, "Seychelles Rupee"},
        {currency_t::SDG, "Sudan Pound"},
        {currency_t::SEK, "Sweden Krona"},
        {currency_t::SGD, "Singapore Dollar"},
        {currency_t::SHP, "Saint Helena Pound"},
        {currency_t::SLL, "Sierra Leone Leone"},
        {currency_t::SOS, "Somalia Shilling"},
        {currency_t::SPL, "Seborga Luigino"},
        {currency_t::SRD, "Suriname Dollar"},
        {currency_t::STN, "São Tomé and Príncipe Dobra"},
        {currency_t::SVC, "El Salvador Colon"},
        {currency_t::SYP, "Syria Pound"},
        {currency_t::SZL, "Swaziland Lilangeni"},
        {currency_t::THB, "Thailand Baht"},
        {currency_t::TJS, "Tajikistan Somoni"},
        {currency_t::TMT, "Turkmenistan Manat"},
        {currency_t::TND, "Tunisia Dinar"},
        {currency_t::TOP, "Tonga Pa'anga"},
        {currency_t::TRY, "Turkey Lira"},
        {currency_t::TTD, "Trinidad and Tobago Dollar"},
        {currency_t::TVD, "Tuvalu Dollar"},
        {currency_t::TWD, "Taiwan New Dollar"},
        {currency_t::TZS, "Tanzania Shilling"},
        {currency_t::UAH, "Ukraine Hryvnia"},
        {currency_t::UGX, "Uganda Shilling"},
        {currency_t::USD, "United States Dollar"},
        {currency_t::UYU, "Uruguay Peso"},
        {currency_t::UZS, "Uzbekistan Som"},
        {currency_t::VEF, "Venezuela Bolívar"},
        {currency_t::VND, "Viet Nam Dong"},
        {currency_t::VUV, "Vanuatu Vatu"},
        {currency_t::WST, "Samoa Tala"},
        {currency_t::XAF, "Communauté Financière Africaine(BEAC) CFA Franc BEAC"},
        {currency_t::XCD, "East Caribbean Dollar"},
        {currency_t::XDR, "International Monetary Fund(IMF) Special Drawing Rights"},
        {currency_t::XOF, "Communauté Financière Africaine(BCEAO) Franc"},
        {currency_t::XPF, "Comptoirs Français du Pacifique(CFP) Franc"},
        {currency_t::YER, "Yemen Rial"},
        {currency_t::ZAR, "South Africa Rand"},
        {currency_t::ZMW, "Zambia Kwacha"},
        {currency_t::ZWD, "Zimbabwe Dollar"}
    };
    std::string to_string(currency_t c) {
        return mc::currency_name.at(c);
    }
}